---
- name: place ssh public key so apiserver can push certs
  authorized_key: user=root key="{{ item }}" state=present
  with_file:
    - '/tmp/id_rsa.pub'
  changed_when: false

- name: Copy certificates directly from the apiserver to nodes
  synchronize: src={{ kube_cert_dir }}/{{ item }} dest={{ kube_cert_dir }}/{{ item }}
  delegate_to: "{{ groups['masters'][0] }}"
  with_items:
    - "ca.crt"
  notify:
    - restart daemons

- name: Copy master tokens to the masters
  synchronize: src={{ kube_token_dir }}/{{ item }} dest={{ kube_token_dir }}/{{ item }}
  delegate_to: "{{ groups['masters'][0] }}"
  with_items:
    - "system:controller_manager.token"
    - "system:scheduler.token"
  notify:
    - restart daemons
  when: inventory_hostname in groups['masters']

- name: Copy node tokens to the nodes
  synchronize: src={{ kube_token_dir }}/{{ item }} dest={{ kube_token_dir }}/{{ item }}
  delegate_to: "{{ groups['masters'][0] }}"
  with_items:
    - "system:kubelet.token"
    - "system:proxy.token"
  notify:
    - restart daemons
  when: inventory_hostname in groups['nodes']

- name: remove ssh public key so apiserver can not push stuff
  authorized_key: user=root key="{{ item }}" state=absent
  with_file:
    - '/tmp/id_rsa.pub'
  changed_when: false
